from stratfunctions import RandoStrat, RandoDist
from blottogame import BlottoGame
import numpy as np

#***********testing the function with given match, alice vs. carol**********

#alice = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
#carol = [15, 5, 30, 5, 10, 5, 0, 10, 0, 20]
#print(BlottoGame(alice, carol, 10))


#*********now lets make some random strat vectors***********
strategies = []

for i in range(1000): #add 100 strategies generated by RandoStrat function
    strategies.append(RandoStrat(100, 10))

for j in range(1000):    #add 100 strategies generated by RandoDist function with a inc size of 5
    strategies.append(RandoDist(100, 10, 2))


scores = []
avgscore = []
for k in range(1000):
    for l in range(1000):
        temp = BlottoGame(strategies[k], strategies[l], 10) #play a game between that strat and every other one
        scores.append(temp)
    avgscore.append(np.mean(scores))    #mean of the scores of that list added to master list of averages
    scores = []     #reset the scores list

print(avgscore)
print(len(avgscore))

index = []      #this will store indices of high scoring vectors
for m in range(1000):
    if avgscore[m] > 5.8:
        index.append(m)

for n in index:
    print(strategies[n])
    print(avgscore[n])






